/* global module */
// Append releases newest-first. Verification values describe observed results only.
// CommonJS matches the root package; applications consume this at build/startup.
module.exports.changelog = [
  {
    version: '0.3.0',
    name: 'SEO and Web Quality Optimization',
    date: '2026-10-05',
    changes: [
      'Add crawlable public HTML, sitemap.xml, robots.txt, route-aware canonicals and metadata.',
      'Add truthful homepage schema, branded Open Graph/Twitter metadata and a 1200x630 sharing image.',
      'Improve public accessibility, mobile navigation, private-route indexing protection and route-level code splitting.',
      'Document SEO operations, performance boundaries, Search Console setup and legitimate backlink strategy.',
    ],
    verification: {
      build: 'PASS',
      typecheck: 'PASS',
      lint: 'PASS',
      tests:
        'PASS — 24 passed, 29 integration tests skipped in the default environment; custom SEO/browser checks passed',
      sitemap: 'PASS — 4 canonical public URLs',
      robots: 'PASS',
      noindexBoundary: 'PASS',
      metadata: 'PASS — titles, descriptions, canonicals, Open Graph, Twitter, homepage JSON-LD',
      publicHtml: 'PASS — static source HTML with one H1 per public page',
      mobileAccessibility: 'PASS — 32 browser checks across 8 widths',
      productionPublic:
        'PASS — 4 public pages, sitemap, robots, private noindex, OG PNG, 404 behavior, public links',
      deployment: 'PASS — v0.3.0, web/API/worker, ports unchanged',
      lighthouse: 'BLOCKED — Lighthouse unavailable in the environment',
      searchConsole: 'MANUAL ACTION REQUIRED',
      backlinks: 'NO ACQUISITIONS CLAIMED',
      formatCheck:
        'FAIL — existing repository-wide Prettier drift remains; changed SEO files were formatted',
      verdict:
        'PARTIAL — implementation and available verification passed; Search Console and Lighthouse require external access/tooling',
    },
  },
  {
    version: '0.2.0',
    name: 'Ownership Records and Administrator Security',
    date: '2026-10-05',
    changes: [
      'Complete item records, document attachment, warranty/repair CRUD, locations and activity.',
      'Add opaque QR/barcode generation/download and local browser scanning/fallback.',
      'Protect administrator HTML/API routes, separate sessions, add owner administration and audited recovery.',
      'Add public help, Terms and Privacy pages.',
    ],
    verification: {
      build: 'PASS',
      typecheck: 'PASS',
      lint: 'PASS',
      tests: 'PASS — 7 root and 43 API tests; none skipped on dedicated PostgreSQL/Redis',
      isolatedBrowserWorkflows: 'PASS',
      interactiveCLIRecovery: 'PASS',
      productionDeployment: 'PASS',
      productionMigration: 'PASS',
      productionContentPreserved: 'PASS',
      webHealth: 'PASS',
      apiHealth: 'PASS',
      workerStartup: 'PASS',
      productionAdministratorRouteProtection:
        'PASS — 9 HTML routes, 10 API endpoints and lazy administrator bundle',
      publicDesktopMobilePages: 'PASS',
      requestProtection: 'PASS',
      googleAuthorizationInitialization: 'PASS',
      discordAuthorizationInitialization: 'PASS',
      googleOAuth: 'BLOCKED — authorized browser/account unavailable',
      discordOAuth: 'BLOCKED — authorized browser/account unavailable',
      authenticatedProductionWorkflows: 'BLOCKED — actual authenticated account unavailable',
      administratorProvisioning: 'FAIL — ADMIN_PASSWORD does not satisfy existing policy',
      smtpAuthentication: 'FAIL — configured SMTP credentials rejected with EAUTH',
      smtpDelivery: 'BLOCKED — SMTP authentication failed',
      pdfUploads: 'BLOCKED — CLAMAV_HOST absent; fail-closed behavior preserved',
      mapsPlacesSearch: 'NOT_CONFIGURED — manual address search and Maps links available',
      physicalCamera: 'NOT_TESTED — image/manual decoding and generated camera frames passed',
      gitSecretCheck: 'PASS',
      verdict:
        'PARTIAL — release deployed and isolated workflows verified; full live authentication/features incomplete',
    },
  },
  {
    version: '0.1.2',
    name: 'Production Deployment and Live Authentication Verification',
    date: '2026-10-05',
    changes: [
      'Deploy the stabilized release using the configured production environment.',
      'Initialize the confirmed production database using the existing reviewed migrations and seed.',
      'Verify real production-domain security, provider initialization and service health.',
      'Bound external Redis/PostgreSQL handshakes after reproducing five-second startup timeouts.',
      'Load the existing environment before production build subprocesses.',
    ],
    verification: {
      build: 'PASS',
      typecheck: 'PASS',
      lint: 'PASS',
      tests: 'PASS — 17 passed, 19 integration tests skipped',
      productionDeployment: 'PASS',
      productionPostgreSQL: 'PASS',
      productionRedis: 'PASS',
      requestProtection: 'PASS',
      csrf: 'PARTIAL — unauthenticated/CORS checks passed; authenticated account unavailable',
      startup: 'PASS',
      googleAuthorizationInitialization: 'PASS',
      discordAuthorizationInitialization: 'PASS',
      googleOAuth: 'BLOCKED — authorized browser/account unavailable',
      discordOAuth: 'BLOCKED — authorized browser/account unavailable',
      authenticatedSession: 'BLOCKED — actual authenticated account unavailable',
      logoutSessionRevocation: 'BLOCKED — actual authenticated account unavailable',
      smtpDelivery: 'BLOCKED — SMTP_PASSWORD absent',
      administratorProvisioning: 'FAIL — ADMIN_PASSWORD does not satisfy existing policy',
      webHealth: 'PASS',
      apiHealth: 'PASS',
      gitSecretCheck: 'PASS',
      verdict: 'FAILED — full authentication verification incomplete',
    },
  },
  {
    version: '0.1.1',
    name: 'Production Authentication Stabilization',
    date: '2026-10-05',
    changes: [
      'Replace production process-tree shutdown with direct Node supervision.',
      'Share verified Redis TLS/SNI options and bounded readiness across security and queues.',
      'Connect Google and Discord controls to safe provider capabilities and session-bound CSRF.',
      'Add versioned build metadata and evidence-based production verification.',
    ],
    verification: {
      build: 'PASS',
      typecheck: 'PASS',
      lint: 'PASS',
      tests: 'PASS',
      googleOAuth: 'FAIL',
      discordOAuth: 'FAIL',
      productionRedis: 'PASS',
      productionPostgreSQL: 'FAIL',
      productionEnvironment: 'FAIL',
      isolatedProductionStartup: 'PASS',
      productionStartup: 'NOT_DEPLOYED',
      productionHealth: 'PASS',
      productionAuthentication: 'FAIL',
    },
  },
  {
    version: '0.1.0',
    name: 'Initial Ovelo Application and Pterodactyl Deployment',
    date: null,
    changes: ['Existing application baseline through commit 1dc18a5.'],
    verification: { historicalChecks: 'NOT_RECORDED' },
  },
];
