/* global module */
// Append releases newest-first. Verification values describe observed results only.
// CommonJS matches the root package; applications consume this at build/startup.
module.exports.changelog = [
  {
    version: '0.4.1',
    name: 'Passwordless Provider Sign-in and Administrator Entry',
    date: '2026-10-06',
    changes: [
      'Create verified Google/Discord accounts after current policy consent without a password or redundant email verification; subsequent sign-ins open the dashboard directly.',
      'Request Discord identify email by default; retain passwordless manual email verification when the provider supplies no verified email.',
      'Reject password registration for pending provider identities and preserve provider-ID account separation and exact-session OAuth completion.',
      'Confirm administrator session and same-origin console entry before navigation; cancel pending sign-in handoffs and keep administrator bootstrap and home navigation on /admin.',
    ],
    verification: {
      build: 'PASS — production build completed for v0.4.1',
      typecheck: 'PASS',
      lint: 'PASS',
      dedicatedApi: 'PASS — 79 tests passed on disposable PostgreSQL/Redis; none skipped',
      isolatedBrowser: 'PASS — 15 workflow groups and 72 admin responsive checks; provider boundary simulated',
      productionDeployment: 'PASS — v0.4.1 web/API/worker started, health 200, ports unchanged and private Discord scope applied',
      productionPublic: 'PASS — 36 responsive public/auth checks, nine admin HTML gates, ten API rejections, bundle gate and secure provider initialization',
      googleOAuth: 'BLOCKED — authorized live browser/account unavailable',
      discordOAuth: 'BLOCKED — authorized live browser/account unavailable',
      administratorLogin: 'PARTIAL — isolated owner entry and all nine console sections passed; live credentials unavailable',
      rootTests: 'PASS — 11 tests including release registry and startup checks',
      defaultApiTests: 'PASS — 37 passed, 42 skipped without disposable services',
      audit: 'PASS — 0 production dependency vulnerabilities',
      secrets: 'PASS — source/configured-value, history, deployed frontend and startup-log checks; ignored environment untracked',
      verdict: 'PARTIAL — passwordless sign-in and administrator console verified in isolation and deployed; authorized live account confirmation unavailable',
    },
  },
  {
    version: '0.4.0',
    name: 'Account Isolation, Consent and Administrator UX',
    date: '2026-10-06',
    changes: [
      'Separate provider sign-in from explicit, initiating-session-bound account linking; rotate replaced sessions and cancel pending OAuth on logout.',
      'Clear private query/local state on identity changes, reject stale authentication responses and synchronize logout across tabs.',
      'Store versioned Terms/Privacy/upload acknowledgements with server enforcement and unchecked, current-version-aware prompts.',
      'Use a dedicated, purpose-bound single-use consent handoff for manual and existing-account OAuth sign-in; preserve administrator OAuth error routing and distinguish corrupt/unsafe/unscanned uploads.',
      'Make ClamAV optional while preserving strict file validation, explicit scanner states, infected-file rejection before storage, cleanup and scanner-state security events.',
      'Confirm OAuth results against the exact issued browser session, expose session-check failures, clear prior identity on incomplete switching and require explicit confirmed linking intent.',
      'Add administrator search/pagination, responsive console/dialog fixes, explicit unconfigured recovery and branded HTTP 404 handling.',
    ],
    verification: {
      build: 'PASS — npm run build completed for v0.4.0',
      typecheck: 'PASS',
      lint: 'PASS',
      dedicatedApi: 'PASS — 77 API tests passed with disposable PostgreSQL/Redis and one worker; no tests skipped',
      isolatedBrowser:
        'PASS — 11 workflow groups, 72 admin checks at 8 widths; simulated provider boundary',
      productionDeployment: 'PASS — v0.4.0, web/API/worker started, ports unchanged, startup log secret check passed',
      productionMigration: 'PASS — 20261005143000_policy_consents applied to production database',
      productionPublic: 'PASS — public routes, HTTPS redirects, HSTS, noindex/private cache boundary, sitemap, robots, favicon, OG image, CORS and 404',
      googleOAuth: 'BLOCKED — authorized live browser/account unavailable',
      discordOAuth: 'BLOCKED — authorized live browser/account unavailable',
      smtpDelivery: 'BLOCKED — previously configured SMTP authentication rejected with EAUTH',
      administratorProvisioning: 'PARTIAL — production query observed 1 active primary administrator; credentialed login was not tested',
      pdfUploads: 'PARTIAL — valid PDF accepted after structural validation with scanner NOT_CONFIGURED in disposable/browser tests; authenticated production upload unavailable and no malware scan claimed',
      rootTests: 'PASS — 11 root tests',
      defaultApiTests: 'PASS — 37 passed, 40 skipped without disposable services',
      audit: 'PASS — 0 production vulnerabilities',
      formatCheck: 'FAIL — repository-wide Prettier drift remains; 78 files are reported and unrelated files were not mass-reformatted',
      lighthouse: 'BLOCKED — unavailable in the environment',
      searchConsole: 'MANUAL ACTION REQUIRED',
      analytics: 'NOT_CONFIGURED — no optional analytics or tracking code is present',
      verdict:
        'PARTIAL — implementation, isolated verification and deployment passed; live provider consent, SMTP delivery, PDF scanning, Lighthouse and Search Console remain blocked/manual',
    },
  },
  {
    version: '0.3.0',
    name: 'SEO and Web Quality Optimization',
    date: '2026-10-05',
    changes: [
      'Add crawlable public HTML, sitemap.xml, robots.txt, route-aware canonicals and metadata.',
      'Add truthful homepage schema, branded Open Graph/Twitter metadata and a 1200x630 sharing image.',
      'Improve public accessibility, mobile navigation, private-route indexing protection and route-level code splitting.',
      'Document SEO operations, performance boundaries, Search Console setup and legitimate backlink strategy.',
    ],
    verification: {
      build: 'PASS',
      typecheck: 'PASS',
      lint: 'PASS',
      tests:
        'PASS — 24 passed, 29 integration tests skipped in the default environment; custom SEO/browser checks passed',
      sitemap: 'PASS — 4 canonical public URLs',
      robots: 'PASS',
      noindexBoundary: 'PASS',
      metadata: 'PASS — titles, descriptions, canonicals, Open Graph, Twitter, homepage JSON-LD',
      publicHtml: 'PASS — static source HTML with one H1 per public page',
      mobileAccessibility: 'PASS — 32 browser checks across 8 widths',
      productionPublic:
        'PASS — 4 public pages, sitemap, robots, private noindex, OG PNG, 404 behavior, public links',
      deployment: 'PASS — v0.3.0, web/API/worker, ports unchanged',
      lighthouse: 'BLOCKED — Lighthouse unavailable in the environment',
      searchConsole: 'MANUAL ACTION REQUIRED',
      backlinks: 'NO ACQUISITIONS CLAIMED',
      formatCheck:
        'FAIL — existing repository-wide Prettier drift remains; changed SEO files were formatted',
      verdict:
        'PARTIAL — implementation and available verification passed; Search Console and Lighthouse require external access/tooling',
    },
  },
  {
    version: '0.2.0',
    name: 'Ownership Records and Administrator Security',
    date: '2026-10-05',
    changes: [
      'Complete item records, document attachment, warranty/repair CRUD, locations and activity.',
      'Add opaque QR/barcode generation/download and local browser scanning/fallback.',
      'Protect administrator HTML/API routes, separate sessions, add owner administration and audited recovery.',
      'Add public help, Terms and Privacy pages.',
    ],
    verification: {
      build: 'PASS',
      typecheck: 'PASS',
      lint: 'PASS',
      tests: 'PASS — 7 root and 43 API tests; none skipped on dedicated PostgreSQL/Redis',
      isolatedBrowserWorkflows: 'PASS',
      interactiveCLIRecovery: 'PASS',
      productionDeployment: 'PASS',
      productionMigration: 'PASS',
      productionContentPreserved: 'PASS',
      webHealth: 'PASS',
      apiHealth: 'PASS',
      workerStartup: 'PASS',
      productionAdministratorRouteProtection:
        'PASS — 9 HTML routes, 10 API endpoints and lazy administrator bundle',
      publicDesktopMobilePages: 'PASS',
      requestProtection: 'PASS',
      googleAuthorizationInitialization: 'PASS',
      discordAuthorizationInitialization: 'PASS',
      googleOAuth: 'BLOCKED — authorized browser/account unavailable',
      discordOAuth: 'BLOCKED — authorized browser/account unavailable',
      authenticatedProductionWorkflows: 'BLOCKED — actual authenticated account unavailable',
      administratorProvisioning: 'FAIL — ADMIN_PASSWORD does not satisfy existing policy',
      smtpAuthentication: 'FAIL — configured SMTP credentials rejected with EAUTH',
      smtpDelivery: 'BLOCKED — SMTP authentication failed',
      pdfUploads: 'BLOCKED — CLAMAV_HOST absent; fail-closed behavior preserved',
      mapsPlacesSearch: 'NOT_CONFIGURED — manual address search and Maps links available',
      physicalCamera: 'NOT_TESTED — image/manual decoding and generated camera frames passed',
      gitSecretCheck: 'PASS',
      verdict:
        'PARTIAL — release deployed and isolated workflows verified; full live authentication/features incomplete',
    },
  },
  {
    version: '0.1.2',
    name: 'Production Deployment and Live Authentication Verification',
    date: '2026-10-05',
    changes: [
      'Deploy the stabilized release using the configured production environment.',
      'Initialize the confirmed production database using the existing reviewed migrations and seed.',
      'Verify real production-domain security, provider initialization and service health.',
      'Bound external Redis/PostgreSQL handshakes after reproducing five-second startup timeouts.',
      'Load the existing environment before production build subprocesses.',
    ],
    verification: {
      build: 'PASS',
      typecheck: 'PASS',
      lint: 'PASS',
      tests: 'PASS — 17 passed, 19 integration tests skipped',
      productionDeployment: 'PASS',
      productionPostgreSQL: 'PASS',
      productionRedis: 'PASS',
      requestProtection: 'PASS',
      csrf: 'PARTIAL — unauthenticated/CORS checks passed; authenticated account unavailable',
      startup: 'PASS',
      googleAuthorizationInitialization: 'PASS',
      discordAuthorizationInitialization: 'PASS',
      googleOAuth: 'BLOCKED — authorized browser/account unavailable',
      discordOAuth: 'BLOCKED — authorized browser/account unavailable',
      authenticatedSession: 'BLOCKED — actual authenticated account unavailable',
      logoutSessionRevocation: 'BLOCKED — actual authenticated account unavailable',
      smtpDelivery: 'BLOCKED — SMTP_PASSWORD absent',
      administratorProvisioning: 'FAIL — ADMIN_PASSWORD does not satisfy existing policy',
      webHealth: 'PASS',
      apiHealth: 'PASS',
      gitSecretCheck: 'PASS',
      verdict: 'FAILED — full authentication verification incomplete',
    },
  },
  {
    version: '0.1.1',
    name: 'Production Authentication Stabilization',
    date: '2026-10-05',
    changes: [
      'Replace production process-tree shutdown with direct Node supervision.',
      'Share verified Redis TLS/SNI options and bounded readiness across security and queues.',
      'Connect Google and Discord controls to safe provider capabilities and session-bound CSRF.',
      'Add versioned build metadata and evidence-based production verification.',
    ],
    verification: {
      build: 'PASS',
      typecheck: 'PASS',
      lint: 'PASS',
      tests: 'PASS',
      googleOAuth: 'FAIL',
      discordOAuth: 'FAIL',
      productionRedis: 'PASS',
      productionPostgreSQL: 'FAIL',
      productionEnvironment: 'FAIL',
      isolatedProductionStartup: 'PASS',
      productionStartup: 'NOT_DEPLOYED',
      productionHealth: 'PASS',
      productionAuthentication: 'FAIL',
    },
  },
  {
    version: '0.1.0',
    name: 'Initial Ovelo Application and Pterodactyl Deployment',
    date: null,
    changes: ['Existing application baseline through commit 1dc18a5.'],
    verification: { historicalChecks: 'NOT_RECORDED' },
  },
];
