import PDFDocument from 'pdfkit';
import { asyncHandler } from '../utils/async-handler.js';
import { assertFeature } from '../services/plan.service.js';
import { prisma } from '../database/prisma.js';
export const propertyReport = asyncHandler(async (req, res) => {
  const userId = req.auth!.userId;
  await assertFeature(userId, 'reports');
  const user = await prisma.user.findUniqueOrThrow({
    where: { id: userId },
    select: { name: true },
  });
  const items = await prisma.item.findMany({
    where: { userId, deletedAt: null },
    select: {
      name: true,
      inventoryCode: true,
      purchasePrice: true,
      estimatedValue: true,
      currency: true,
      serialNumber: true,
      category: { select: { name: true } },
      location: { select: { name: true } },
    },
    orderBy: { createdAt: 'desc' },
  });
  res.setHeader('content-type', 'application/pdf');
  res.setHeader('content-disposition', 'attachment; filename="ovelo-property-inventory.pdf"');
  const doc = new PDFDocument({ margin: 48, size: 'A4' });
  doc.pipe(res);
  doc.fillColor('#1b241c').fontSize(22).font('Helvetica-Bold').text('MY PROPERTY INVENTORY');
  doc
    .moveDown(0.4)
    .fillColor('#68736c')
    .fontSize(10)
    .font('Helvetica')
    .text(`Prepared for ${user.name} · ${new Date().toLocaleDateString()}`);
  doc.moveDown(1.4);
  doc
    .fillColor('#1b241c')
    .fontSize(9)
    .font('Helvetica-Bold')
    .text('CATEGORY', 48, doc.y, { continued: true, width: 90 })
    .text('ITEM', { continued: true, width: 150 })
    .text('PURCHASE', { continued: true, width: 85 })
    .text('EST. VALUE', { continued: true, width: 85 })
    .text('LOCATION', { width: 100 });
  doc.moveDown(0.5);
  doc.strokeColor('#dfe4df').moveTo(48, doc.y).lineTo(547, doc.y).stroke();
  doc.moveDown(0.45);
  for (const item of items) {
    const y = doc.y;
    doc
      .fillColor('#29322d')
      .font('Helvetica')
      .fontSize(8)
      .text(item.category?.name ?? 'Other', 48, y, { width: 90, continued: true })
      .text(item.name.slice(0, 35), { width: 150, continued: true })
      .text(item.purchasePrice ? `${item.purchasePrice} ${item.currency}` : '—', {
        width: 85,
        continued: true,
      })
      .text(item.estimatedValue ? `${item.estimatedValue} ${item.currency}` : '—', {
        width: 85,
        continued: true,
      })
      .text(item.location?.name ?? '—', { width: 100 });
    doc.moveDown(0.6);
  }
  if (!items.length) doc.fillColor('#68736c').fontSize(11).text('No items have been added yet.');
  doc.moveDown(2);
  doc
    .fillColor('#68736c')
    .fontSize(8)
    .text(
      'Values are user-entered estimates and do not represent market valuation. Generated by Ovelo — Know what you own.',
    );
  doc.end();
});
