import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { downloadFile, fileBlob, post } from '../../lib/api';
import { Button } from '../../components/Button';
type Code = { revokedAt: string | null; expiresAt: string | null };
const active = (c: Code) => !c.revokedAt && (!c.expiresAt || new Date(c.expiresAt).getTime() > Date.now());
export function Identification({ itemId, qr, barcodes, onChange }: { itemId: string; qr: (Code & { code: string }) | null; barcodes: (Code & { value: string })[]; onChange: () => Promise<unknown> }) {
  const [previews, setPreviews] = useState<Record<string, string>>({}), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const qrActive = !!qr && active(qr), barcode = barcodes.find(b => b.value.startsWith('OVELO-') && active(b));
  useEffect(() => { let mounted = true; const urls: string[] = []; setPreviews({}); setError(''); for (const [kind, valid] of [['qr', qrActive], ['barcode', !!barcode]] as const) if (valid) void fileBlob(`/items/${itemId}/${kind}`).then(blob => { const url = URL.createObjectURL(blob); urls.push(url); if (mounted) setPreviews(s => ({ ...s, [kind]: url })); else URL.revokeObjectURL(url); }).catch(e => { if (mounted) setError(e.message); }); return () => { mounted = false; urls.forEach(url => URL.revokeObjectURL(url)); }; }, [itemId, qr?.code, barcode?.value, qrActive, !!barcode]);
  async function action(fn: () => Promise<unknown>) { setBusy(true); setError(''); try { await fn(); await onChange(); } catch (e) { setError(e instanceof Error ? e.message : 'Identification action failed.'); } finally { setBusy(false); } }
  return <section className="detail-section"><div className="section-head"><div><span className="eyebrow">IDENTIFICATION</span><h3>QR Code & Barcode</h3></div><Link className="button button-ghost" to="/scan">Scan</Link></div><p>Opaque codes identify this record. Scanning always requires an authorized Ovelo account.</p>{error && <p role="alert" className="form-alert">{error}</p>}<div className="identification-grid">{(['qr', 'barcode'] as const).map(kind => <div className="identifier-card" key={kind}><h4>{kind === 'qr' ? 'QR Code' : 'Barcode'}</h4>{previews[kind] ? <img src={previews[kind]} alt={`${kind} for this item`} /> : <p>{(kind === 'qr' ? qrActive : !!barcode) ? 'Loading preview…' : 'No active code generated.'}</p>}<Button disabled={busy} onClick={() => { const existing = kind === 'qr' ? qrActive : !!barcode; if (!existing || window.confirm('Regenerate this code? Existing printed codes will stop resolving.')) void action(() => post(`/items/${itemId}/${kind}`, {})); }}>Generate {kind === 'qr' ? 'QR Code' : 'Barcode'}</Button>{(kind === 'qr' ? qrActive : !!barcode) && <div className="record-actions">{(['png', 'svg'] as const).map(format => <Button key={format} variant="ghost" disabled={busy} onClick={() => void action(() => downloadFile(`/items/${itemId}/${kind}?format=${format}&download=true`, `ovelo-${kind}.${format}`))}>Download {format.toUpperCase()}</Button>)}</div>}</div>)}</div></section>;
}
