import { useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, Pencil, Plus } from 'lucide-react';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { useState } from 'react';
import { del, get } from '../lib/api';
import type { DocumentRecord, Place, Repair, Warranty } from '../lib/records';
import { displayDate, warrantyStatus } from '../lib/records';
import { Loading } from '../components/Loading';
import { Badge } from '../components/Badge';
import { Button } from '../components/Button';
import { DocumentList } from '../features/records/DocumentList';
import { RecordForm } from '../features/records/RecordForm';
import { Identification } from '../features/records/Identification';
export type ItemDetailRecord = {
  id: string; inventoryCode: string; name: string; description: string | null; condition: string | null; status: string;
  purchaseDate: string | null; purchasePrice: string | null; estimatedValue: string | null; currency: string; store: string | null;
  serialNumber: string | null; modelNumber: string | null; manufacturer: string | null; notes: string | null; createdAt: string; updatedAt: string;
  category: { id: string; name: string } | null; location: Place | null; warranties: Warranty[]; repairs: Repair[];
  qrCode: { code: string; revokedAt: string | null; expiresAt: string | null } | null;
  barcodes: { value: string; revokedAt: string | null; expiresAt: string | null }[];
  _count: { documents: number; repairs: number };
};
const tabs = ['overview', 'documents', 'warranty', 'repairs', 'activity'] as const;
export function ItemDetail() {
  const { id } = useParams(); const client = useQueryClient(); const navigate = useNavigate(); const [params, setParams] = useSearchParams();
  const selected = params.get('tab') || 'overview'; const tab = tabs.includes(selected as typeof tabs[number]) ? selected : 'overview';
  const [editing, setEditing] = useState<{ kind: 'warranty' | 'repair'; record?: Warranty | Repair }>();
  const [error, setError] = useState(''), [busy, setBusy] = useState(false), [message, setMessage] = useState('');
  const query = useQuery({ queryKey: ['item', id], queryFn: () => get<{ data: ItemDetailRecord }>(`/items/${id}`), enabled: !!id });
  const docs = useQuery({ queryKey: ['documents', id], queryFn: () => get<{ data: DocumentRecord[] }>(`/items/${id}/documents`), enabled: !!id });
  const activity = useQuery({ queryKey: ['item-activity', id], queryFn: () => get<{ data: { id: string; action: string; description: string; createdAt: string }[] }>(`/items/${id}/activity`), enabled: !!id });
  async function refresh() { await Promise.all([client.invalidateQueries({ queryKey: ['item', id] }), client.invalidateQueries({ queryKey: ['documents'] }), client.invalidateQueries({ queryKey: ['item-activity', id] }), client.invalidateQueries({ queryKey: ['locations'] })]); }
  async function remove(path: string, label: string) { if (!window.confirm(`Delete this ${label}?`)) return; setBusy(true); setError(''); try { await del(path); await refresh(); setMessage(`${label} deleted.`); } catch (e) { setError(e instanceof Error ? e.message : 'Could not delete record.'); } finally { setBusy(false); } }
  if (query.isPending) return <Loading rows={8} />;
  if (query.error || !query.data) return <div className="page-error">This item could not be found. <Link to="/inventory">Return to inventory</Link></div>;
  const item = query.data.data, documents = docs.data?.data || [];
  return <div className="detail-page"><Link className="back-link" to="/inventory"><ArrowLeft size={15} />Back to inventory</Link>
    <div className="detail-hero"><div className="detail-art"><span>{item.name[0]?.toUpperCase()}</span></div><div className="detail-title"><div className="detail-title-row"><Badge tone={item.status === 'OWNED' ? 'green' : 'neutral'}>{item.status.toLowerCase()}</Badge><span className="detail-id">{item.inventoryCode}</span></div><h2>{item.name}</h2><p>{[item.manufacturer, item.modelNumber, item.category?.name].filter(Boolean).join(' · ') || 'Uncategorized item'}</p></div><div className="detail-actions"><Link className="button button-ghost" to={`/item/${id}/edit`}><Pencil size={16} />Edit</Link><Button variant="ghost" disabled={busy} onClick={() => { if (window.confirm('Archive this item? Its ownership history will be retained.')) { setBusy(true); void del(`/items/${id}`).then(() => navigate('/inventory')).catch(e => { setError(e.message); setBusy(false); }); } }}>Archive</Button></div></div>
    {error && <p className="form-alert" role="alert">{error}</p>}{message && <p className="success-note" role="status">{message}</p>}
    <div className="detail-grid"><section className="detail-main"><div className="detail-tabs" role="tablist" aria-label="Item records">{tabs.map(t => <button key={t} id={`tab-${t}`} role="tab" aria-selected={tab === t} aria-controls={`panel-${t}`} className={tab === t ? 'active' : ''} onClick={() => setParams({ tab: t })} onKeyDown={e => { if (['ArrowLeft', 'ArrowRight', 'Home', 'End'].includes(e.key)) { e.preventDefault(); const next = e.key === 'Home' ? 0 : e.key === 'End' ? tabs.length - 1 : (tabs.indexOf(t) + (e.key === 'ArrowRight' ? 1 : -1) + tabs.length) % tabs.length; setParams({ tab: tabs[next]! }); document.getElementById(`tab-${tabs[next]}`)?.focus(); } }}>{t[0]!.toUpperCase() + t.slice(1)}{t === 'documents' && <span>{item._count.documents}</span>}{t === 'repairs' && <span>{item.repairs.length}</span>}</button>)}</div>
    <div className="detail-sections" id={`panel-${tab}`} role="tabpanel" aria-labelledby={`tab-${tab}`}>
    {tab === 'overview' && <><section className="detail-section"><div className="section-head"><div><span className="eyebrow">THE BASICS</span><h3>Ownership details</h3></div></div><div className="detail-facts">{[['Name', item.name], ['Category', item.category?.name], ['Brand', item.manufacturer], ['Model', item.modelNumber], ['Serial number', item.serialNumber], ['Condition', item.condition], ['Purchase date', displayDate(item.purchaseDate)], ['Purchased from', item.store], ['Purchase price', item.purchasePrice ? `${item.purchasePrice} ${item.currency}` : null], ['Current value', item.estimatedValue ? `${item.estimatedValue} ${item.currency}` : null]].map(([label, value]) => <div className="fact" key={label}><span>{label}</span><strong>{value || 'Not recorded'}</strong></div>)}</div>{item.description && <p>{item.description}</p>}{item.notes && <p className="record-notes">{item.notes}</p>}</section>
      <section className="detail-section"><h3>Location</h3>{item.location ? <><strong>{item.location.name}</strong>{item.location.address && <p>{item.location.address}</p>}{item.location.mapsUrl && <a className="text-link" href={item.location.mapsUrl} target="_blank" rel="noopener noreferrer">Open in Google Maps ↗</a>}</> : <p>No location recorded. <Link to={`/item/${id}/edit`}>Add location</Link></p>}</section>
      <section className="detail-section"><h3>Supporting records</h3><div className="summary-links"><button onClick={() => setParams({ tab: 'documents' })}>{item._count.documents} documents</button><button onClick={() => setParams({ tab: 'warranty' })}>{item.warranties.length} warranties{item.warranties[0] && ` · ${warrantyStatus(item.warranties[0])}`}</button><button onClick={() => setParams({ tab: 'repairs' })}>{item.repairs.length} repairs</button></div></section>
      <Identification itemId={item.id} qr={item.qrCode} barcodes={item.barcodes} onChange={refresh} />
      <section className="detail-section"><div className="section-head"><h3>Recent activity</h3><button className="text-button" onClick={() => setParams({ tab: 'activity' })}>View all</button></div><Activity rows={activity.data?.data.slice(0, 5) || []} error={!!activity.error} /></section></>}
    {tab === 'documents' && <section className="detail-section"><h3>Documents</h3>{docs.isPending ? <Loading rows={3} /> : docs.error ? <p role="alert" className="form-alert">Unable to load documents. <button onClick={() => void docs.refetch()}>Retry</button></p> : <DocumentList documents={documents} itemId={item.id} onChange={refresh} />}</section>}
    {tab === 'warranty' && <section className="detail-section"><div className="section-head"><h3>Warranty</h3><Button onClick={() => setEditing({ kind: 'warranty' })}><Plus size={15} />Add warranty</Button></div>{!item.warranties.length && <p className="inline-empty">No warranty details attached yet.</p>}{item.warranties.map(w => <article className="record-card" key={w.id}><div><h3>{w.provider || 'Warranty coverage'}</h3><Badge tone={warrantyStatus(w) === 'Active' ? 'green' : 'amber'}>{warrantyStatus(w)}</Badge><p>{displayDate(w.startDate)} — {displayDate(w.endDate)}</p><p>{[w.planType, w.warrantyNumber].filter(Boolean).join(' · ')}</p><p className="record-notes">{w.coverage}</p><p className="record-notes">{w.notes}</p><Attachments ids={w.documents.map(d => d.documentId)} documents={documents} /></div><div className="record-actions"><Button variant="ghost" onClick={() => setEditing({ kind: 'warranty', record: w })}>Edit</Button><Button variant="ghost" disabled={busy} onClick={() => void remove(`/items/${id}/warranties/${w.id}`, 'warranty')}>Delete</Button></div></article>)}</section>}
    {tab === 'repairs' && <section className="detail-section"><div className="section-head"><h3>Repairs</h3><Button onClick={() => setEditing({ kind: 'repair' })}><Plus size={15} />Add repair</Button></div>{!item.repairs.length && <p className="inline-empty">No repairs recorded.</p>}{item.repairs.map(r => <article className="record-card" key={r.id}><div><h3>{r.problem}</h3><p>{displayDate(r.date)} · {r.repairShop || 'Provider not recorded'} · {r.cost} {r.currency}</p><p className="record-notes">{r.description}</p><p className="record-notes">{r.notes}</p><Attachments ids={r.documents.map(d => d.documentId)} documents={documents} /></div><div className="record-actions"><Button variant="ghost" onClick={() => setEditing({ kind: 'repair', record: r })}>Edit</Button><Button variant="ghost" disabled={busy} onClick={() => void remove(`/items/${id}/repairs/${r.id}`, 'repair')}>Delete</Button></div></article>)}</section>}
    {tab === 'activity' && <section className="detail-section"><h3>Item activity</h3>{activity.isPending ? <Loading rows={3} /> : <Activity rows={activity.data?.data || []} error={!!activity.error} />}</section>}
    </div></section><aside className="detail-aside"><div className="aside-card ownership-card"><span className="eyebrow">OWNED SINCE</span><strong>{displayDate(item.createdAt)}</strong><p>Changes are retained in your ownership history.</p><div className="aside-rule" /><span className="eyebrow">INVENTORY ID</span><code>{item.inventoryCode}</code></div><div className="aside-card"><span className="eyebrow">LAST UPDATED</span><strong>{displayDate(item.updatedAt)}</strong></div></aside></div>
    {editing && <RecordForm kind={editing.kind} record={editing.record} itemId={item.id} currency={item.currency} documents={documents} onClose={() => setEditing(undefined)} onSaved={async () => { await refresh(); setMessage(`${editing.kind} saved.`); }} />}
  </div>;
}
function Activity({ rows, error }: { rows: { id: string; action: string; description: string; createdAt: string }[]; error: boolean }) { return error ? <p role="alert">Activity could not be loaded.</p> : rows.length ? <ol className="record-timeline">{rows.map(a => <li key={a.id}><strong>{a.description}</strong><small>{displayDate(a.createdAt)} · {a.action.toLowerCase().replace(/_/g, ' ')}</small></li>)}</ol> : <p>No item activity recorded.</p>; }
function Attachments({ ids, documents }: { ids: string[]; documents: DocumentRecord[] }) { return <ul>{documents.filter(d => ids.includes(d.id)).map(d => <li key={d.id}><Link to={`?tab=documents`}>{d.title}</Link></li>)}</ul>; }
